Repository unb-mds/2025-1-GovInsights, pull requests merged in 2025-05, with the labels that each got.

#49 Feature/pesquisar codigo
  src/models/search.py
Labels: feature

#50 docs: altera user story sobre filtragem na documentação de Levantamen…
  Documentacao/LevantamentoRequisitos/02_backlog.md
  Documentacao/LevantamentoRequisitos/04_requisitos.md
Labels: documentation

#60 Develop
  .github/Commit/Commit_template.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/tarefa.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/ci.yml
  Documentacao/Arquitetura/Alterações na Arquitetura/alteracao_01/alteracao_01.md
  Documentacao/Arquitetura/Alterações na Arquitetura/alteracao_01/image.png
  Documentacao/Arquitetura/Alterações na Arquitetura/alteracao_02/alteracao_02.md
  Documentacao/Arquitetura/Alterações na Arquitetura/alteracao_02/image.png
  Documentacao/GitPages/docs/Como-contribuir/Como-contribuir.md
  Documentacao/GitPages/docs/Projeto/Projeto.md
  Documentacao/GitPages/docs/Sobre/Sobre.md
  Documentacao/GitPages/docs/Sprints/Sprint0.md
  Documentacao/GitPages/docs/Sprints/Sprint01.md
  Documentacao/GitPages/docs/Sprints/Sprint02.md
  Documentacao/GitPages/docs/Sprints/Sprint03.md
  Documentacao/GitPages/docs/Sprints/Sprint04.md
  Documentacao/GitPages/docs/Sprints/Sprint05.md
  Documentacao/GitPages/docs/assets/extra.css
  Documentacao/GitPages/docs/index.md
  Documentacao/GitPages/mkdocs.yml
  Documentacao/Levantamento de Requisitos/01_visao_produto.md
  Documentacao/Levantamento de Requisitos/02_backlog.md
  Documentacao/Levantamento de Requisitos/03_jornada_usuario.md
  Documentacao/Levantamento de Requisitos/04_requisitos.md
  Documentacao/Levantamento de Requisitos/05_documentacao_tecnica.md
  Documentacao/Levantamento de Requisitos/06_estrategia_releases.md
  Documentacao/Planejamento/cronograma.md
  Documentacao/Planejamento/scrum.md
  Documentacao/Protótipo/esboco-interface-exportacao.md
  Documentacao/Protótipo/esboço-interface-inicial.md
  Documentacao/assets/logo.png
  Documentacao/index.md
  Documentacao/stylesheets/extra.css
  mkdocs.yml
  requirements.txt
Labels: documentation, feature

#68 Develop
  Documentacao/Arquitetura/Alterações na Arquitetura/alteracao_01/alteracao_01.md
  Documentacao/Arquitetura/Alterações na Arquitetura/alteracao_01/image.png
  Documentacao/Arquitetura/Alterações na Arquitetura/alteracao_02/alteracao_02.md
  Documentacao/Arquitetura/Alterações na Arquitetura/alteracao_02/image.png
  Documentacao/Arquitetura/README.md
  Documentacao/Arquitetura/diagramas/arquitetura.png
  Documentacao/Arquitetura/diagramas/estrutura.png
  Documentacao/Arquitetura/diagramas/pastas.png
  Documentacao/GitPages/docs/Como-contribuir/Como-contribuir.md
  Documentacao/GitPages/docs/Projeto/Projeto.md
  Documentacao/GitPages/docs/Sobre/Sobre.md
  Documentacao/GitPages/docs/Sprints/Sprint0.md
  Documentacao/GitPages/docs/Sprints/Sprint01.md
  Documentacao/GitPages/docs/Sprints/Sprint02.md
  Documentacao/GitPages/docs/Sprints/Sprint03.md
  Documentacao/GitPages/docs/Sprints/Sprint04.md
  Documentacao/GitPages/docs/Sprints/Sprint05.md
  Documentacao/GitPages/docs/assets/extra.css
  Documentacao/GitPages/docs/index.md
  Documentacao/GitPages/mkdocs.yml
  Documentacao/Levantamento de Requisitos/01_visao_produto.md
  Documentacao/Levantamento de Requisitos/02_backlog.md
  Documentacao/Levantamento de Requisitos/03_jornada_usuario.md
  Documentacao/Levantamento de Requisitos/04_requisitos.md
  Documentacao/Levantamento de Requisitos/05_documentacao_tecnica.md
  Documentacao/Levantamento de Requisitos/06_estrategia_releases.md
  README.md
  src/estrutura.txt
  src/models/README.md
  src/services/search.py
  src/workers/README.md
Labels: documentation

#78 📝 docs: ajustes textuais nos arquivos de visão do produto e índice
  Documentacao/Levantamento de Requisitos/01_visao_produto.md
  Documentacao/index.md
Labels: documentation

#88 docs: atualização cronograma
  Documentacao/Levantamento de Requisitos/02_backlog.md
  Documentacao/Planejamento/cronograma.md
  src/interface/views/__pycache__/alertas.cpython-313.pyc
  src/interface/views/__pycache__/analises.cpython-313.pyc
  src/interface/views/__pycache__/configuracoes.cpython-313.pyc
  src/interface/views/__pycache__/dados.cpython-313.pyc
  src/interface/views/__pycache__/relatorios.cpython-313.pyc
  src/interface/views/__pycache__/user.cpython-313.pyc
Labels: documentation

#89 feature: login implementado no app.py
  .gitignore
  src/interface/views/app.py
Labels: documentation

#92 Atualização de atas e revisões de Sprints
  Documentacao/Atas/Sprint06.md
  Documentacao/Atas/Sprint07.md
  Documentacao/Planejamento/Revisões Sprints/revisao-sprint6.md
  Documentacao/Planejamento/Revisões Sprints/revisao-sprint7.md
Labels: documentation

#87 Develop
  .gitignore
  Documentacao/Atas/Sprint04.md
  Documentacao/Atas/Sprint05.md
  Documentacao/Atas/Sprint06.md
  Documentacao/Atas/Sprint07.md
  Documentacao/Levantamento de Requisitos/02_backlog.md
  Documentacao/Planejamento/Revisões Sprints/revisao-sprint0.md
  Documentacao/Planejamento/Revisões Sprints/revisao-sprint1.md
  Documentacao/Planejamento/Revisões Sprints/revisao-sprint2.md
  Documentacao/Planejamento/Revisões Sprints/revisao-sprint3.md
  Documentacao/Planejamento/Revisões Sprints/revisao-sprint4.md
  Documentacao/Planejamento/Revisões Sprints/revisao-sprint5.md
  Documentacao/Planejamento/Revisões Sprints/revisao-sprint6.md
  Documentacao/Planejamento/Revisões Sprints/revisao-sprint7.md
  Documentacao/Planejamento/cronograma.md
  src/interface/views/__pycache__/alertas.cpython-313.pyc
  src/interface/views/__pycache__/analises.cpython-313.pyc
  src/interface/views/__pycache__/configuracoes.cpython-313.pyc
  src/interface/views/__pycache__/dados.cpython-313.pyc
  src/interface/views/__pycache__/relatorios.cpython-313.pyc
  src/interface/views/__pycache__/user.cpython-313.pyc
  src/interface/views/app.py
  src/services/search.py
Labels: feature

#98 docs: adicionando ata de reunião
  Documentacao/Atas/Sprint08.md
Labels: documentation

#112 Implementação do Banco de Dados
  requirements.txt
  src/data/connect.py
  src/data/database_operation.py
Labels: feature, alta prioridade, alerta, Backend

#101 Feature/mistral 7b
  src/interface/views/app.py
  src/interface/views/mistral_report_generator.py
  src/interface/views/relatorios.py
Labels: alta prioridade
