Repository unb-mds/2025-1-GovInsights, pull requests merged in 2025-06, with the labels that each got.

#126 Features/new views
  .gitignore
  .streamlit/config.toml
  src/interface/new-views/assets/font
  src/interface/new-views/assets/stylesheets/style.css
  src/interface/new-views/dashboard.py
  src/interface/new-views/static/font/Inter-VariableFont.ttf
  src/services/__init__.py
  src/services/graph.py
  src/services/search.py
Labels: design, feature, alta prioridade, visualização, Integração, Backend, Frontend, Filtro

#132 docs: adicionando ata de reunião
  Documentacao/Atas/Sprint09.md
Labels: documentation

#139 Feature/documentacao – Adicionando backlog
  Documentacao/Planejamento/Backlog.md
Labels: documentation, Gestão de Projeto, Backlog

#144 Feature/documentacao - Estudo: Estratégia e Desenvolvimento de Testes Automatizados para GovInsights
  Documentacao/Estudos/Testes/Estudo.md
Labels: study, testing, Gestão de Projeto, Concluído

#159 Frontend - Correção da cor de fundo dos gráficos
  .streamlit/config.toml
  src/interface/views/assets/stylesheets/style.css
Labels: bug, Frontend

#163 feat: mudanca na ordem na chamada da dash
  src/interface/views/dashboard.py
Labels: bug, Deploy

#165 Funcionalidade de Serviço Assíncrono
  .github/workflows/cronjob.yml
  cronjob_runner.py
  requirements-cron.txt
  requirements.txt
  src/data/database_operation.py
  src/data/operacoes_bd.py
  src/services/async_service/cronJob.py
Labels: feature, alta prioridade, alerta, Backend

#164 # 🚀 Implementação da Infraestrutura Inicial de Testes e Refatoração da Lógica de Relatórios
  .github/workflows/ci.yml
  src/__pycache__/__init__.cpython-313.pyc
  src/core/__pycache__/__init__.cpython-313.pyc
  src/core/__pycache__/data_providers.cpython-313.pyc
  src/core/__pycache__/report_logic.cpython-313.pyc
  src/core/report_logic.py
  src/services/__pycache__/search.cpython-313.pyc
  tests/__pycache__/__init__.cpython-313.pyc
  tests/unit/__pycache__/__init__.cpython-313.pyc
  tests/unit/__pycache__/test_core_report_logic_unit.cpython-313-pytest-8.4.0.pyc
  tests/unit/__pycache__/test_data_providers_unit.cpython-313-pytest-8.4.0.pyc
  tests/unit/__pycache__/test_relatorios_page_unit.cpython-313-pytest-8.4.0.pyc
  tests/unit/__pycache__/test_search_unit.cpython-313-pytest-8.4.0.pyc
  tests/unit/test_core_report_logic_unit.py
  tests/unit/test_relatorios_page_unit.py
Labels: testing

#170 Correções e atualizações tela de alertas
  src/interface/views/assets/stylesheets/style2.css
Labels: baixa prioridade, Frontend

#171 Release: v1.2.1 - Merge Develop into Main
  .github/workflows/ci.yml
  .github/workflows/cronjob.yml
  .streamlit/config.toml
  Documentacao/Atas/Sprint11.md
  Documentacao/Estudos/Testes/Estudo.md
  Documentacao/Planejamento/Revisões Sprints/revisao-sprint10.md
  Documentacao/Planejamento/Revisões Sprints/revisao-sprint11.md
  cronjob_runner.py
  pytest.ini
  requirements-app.txt
  requirements-cron.txt
  requirements.txt
  src/__init__.py
  src/__pycache__/__init__.cpython-313.pyc
  src/core/__init__.py
  src/core/__pycache__/__init__.cpython-313.pyc
  src/core/__pycache__/data_providers.cpython-313.pyc
  src/core/__pycache__/report_logic.cpython-313.pyc
  src/core/data_providers.py
  src/core/report_logic.py
  src/data/database_operation.py
  src/data/operacoes_bd.py
  src/interface/views/alertas.py
  src/interface/views/assets/stylesheets/mainStyle.css
  src/interface/views/assets/stylesheets/style.css
  src/interface/views/assets/stylesheets/style2.css
  src/interface/views/dashboard.py
  src/main.py
  src/services/__init__.py
  src/services/__pycache__/search.cpython-313.pyc
  src/services/async_service/cronJob.py
  src/services/graph.py
  src/services/search.py
  test/test_graph.py
  tests/__init__.py
  tests/__pycache__/__init__.cpython-313.pyc
  tests/integration/__init__.py
  tests/unit/__init__.py
  tests/unit/__pycache__/__init__.cpython-313.pyc
  tests/unit/__pycache__/test_core_report_logic_unit.cpython-313-pytest-8.4.0.pyc
  tests/unit/__pycache__/test_data_providers_unit.cpython-313-pytest-8.4.0.pyc
  tests/unit/__pycache__/test_relatorios_page_unit.cpython-313-pytest-8.4.0.pyc
  tests/unit/__pycache__/test_search_unit.cpython-313-pytest-8.4.0.pyc
  tests/unit/test_core_report_logic_unit.py
  tests/unit/test_data_providers_unit.py
  tests/unit/test_relatorios_page_unit.py
  tests/unit/test_search_unit.py
Labels: alta prioridade, validação, Homologação, Deploy

#174 chore(tests): remove unused test_graph.py
  test/test_graph.py
Labels: baixa prioridade
