Repository unb-mds/2025-1-GovInsights, pull requests merged in 2025-07, with the labels that each got.

#179 feat(tests): remover arquivos pycache e atualizar requirements.txt
  requirements.txt
  src/__pycache__/__init__.cpython-313.pyc
  src/core/__pycache__/__init__.cpython-313.pyc
  src/core/__pycache__/data_providers.cpython-313.pyc
  src/core/__pycache__/report_logic.cpython-313.pyc
  src/services/__pycache__/search.cpython-313.pyc
  tests/__pycache__/__init__.cpython-313.pyc
  tests/unit/__pycache__/__init__.cpython-313.pyc
Labels: bug, testing, ci/cd

#180 fix(tests): corrigir mocks dos testes unitários
  tests/unit/test_ia_unit.py
  tests/unit/test_pdf_unit.py
Labels: bug, testing, ci/cd

#182 Update keep-alive.yml
  .github/workflows/keep-alive.yml
Labels: bug, Deploy

#185 bugfix: corrige keyerror do current_value na página principal da dash…
  src/interface/views/dashboard.py
Labels: bug

#189 feat(tests): Implementa suíte completa de testes de integração e refatoração geral
  .github/workflows/ci.yml
  pytest.ini
  test_analysis/CORRECAO_FINAL_MOCKS_CONCLUIDA.md
  test_analysis/CORRECAO_PERFORMANCE_CONCLUIDA.md
  test_analysis/LIMPEZA_FINAL_DOCUMENTACAO.md
  test_analysis/README.md
  test_analysis/data/coverage/coverage_report.txt
  test_analysis/data/json_reports/debug_analysis_data.json
  test_analysis/data/json_reports/final_integration_test_report.json
  test_analysis/data/json_reports/quick_test_report.json
  test_analysis/docs/GUIA_ESTRUTURA.md
  test_analysis/docs/GUIA_INICIAL.md
  test_analysis/docs/MIGRACAO.md
  test_analysis/docs/USO_SCRIPTS.md
  test_analysis/integration_tests/__init__.py
  test_analysis/integration_tests/test_database_integration.py
  test_analysis/integration_tests/test_end_to_end_workflow.py
  test_analysis/integration_tests/test_ia_api_integration.py
  test_analysis/integration_tests/test_ipea_search_integration.py
  test_analysis/integration_tests/test_pdf_generation_integration.py
  test_analysis/integration_tests/test_search_graph_ia_pipeline.py
  test_analysis/integration_tests/test_streamlit_backend_integration.py
  test_analysis/integration_tests/test_validation.py
  test_analysis/reports/test_integration_fixes_report.md
  test_analysis/scripts/consolidated_test_report.py
  test_analysis/scripts/final_consolidated_test_report.py
  test_analysis/scripts/fixes/fix_buscar_indicadores.py
  test_analysis/scripts/fixes/fix_encoding.py
  test_analysis/scripts/fixes/fix_end_to_end_tests.py
  test_analysis/scripts/infrastructure/test_basic_infrastructure.py
  test_analysis/scripts/infrastructure/test_imports_integration.py
  test_analysis/scripts/infrastructure/test_integration_health.py
  test_analysis/scripts/test_ci_simulation.py
  test_analysis/scripts/validation/CONCLUSAO_FINAL_SUCESSO.py
  test_analysis/scripts/validation/RELATORIO_COBERTURA_FINAL.py
  test_analysis/scripts/validation/analyze_test_coverage.py
  test_analysis/scripts/validation/comprehensive_test_analyzer.py
  test_analysis/scripts/validation/fix_integration_tests.py
  test_analysis/scripts/validation/fix_unnecessary_skips.py
  test_analysis/scripts/validation/post_migration_validation.py
  test_analysis/scripts/validation/quick_test_analysis.py
  test_analysis/scripts/validation/run_final_integration_tests.py
  test_analysis/scripts/validation/validate_integration_tests.py
  tests/fixtures/__init__.py
  tests/fixtures/mock_data.py
  tests/fixtures/test_config.py
  tests/integration/test_database_integration.py
  tests/integration/test_end_to_end_workflow.py
  tests/integration/test_ia_api_integration.py
  tests/integration/test_ipea_search_integration.py
  tests/integration/test_pdf_generation_integration.py
  tests/integration/test_search_graph_ia_pipeline.py
  tests/integration/test_streamlit_backend_integration.py
  tests/integration/test_validation.py
  tests/unit/test_main_unit.py
Labels: documentation, testing, ci/cd

#191 Implementação Função de Deleção no BD
  src/data/operacoes_bd.py
Labels: feature, alta prioridade, Backend
